[versions]
kotlin = "2.3.0"

# Spring
spring-boot = "4.0.2"
spring-dependency-management = "1.1.7"

# Database
exposed = "1.0.0"
postgres = "42.7.8"

# Utils
kotlin-logger = "7.0.14"
cuid = "2.0.5"
konform = "0.11.0"

# Testing
kotest = "6.0.7"
mockk = "1.14.7"
testcontainers = "2.0.3"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }

spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }

[libraries]
############################
# Spring Boot Starters
############################
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-security-oauth2-client = { module = "org.springframework.boot:spring-boot-starter-security-oauth2-client" }
spring-boot-starter-security-oauth2-resource-server = { module = "org.springframework.boot:spring-boot-starter-security-oauth2-resource-server" }

############################
# Kotlin / Jackson
############################

jackson-kotlin = { module = "tools.jackson.module:jackson-module-kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }

############################
# Utils
############################
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logger" }
cuid = { module = "io.github.thibaultmeyer:cuid", version.ref = "cuid" }
konform = { module = "io.konform:konform", version.ref = "konform" }

############################
# Database
############################
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
exposed-spring-boot-starter = { module = "org.jetbrains.exposed:exposed-spring-boot4-starter", version.ref = "exposed" }
postgres-driver = { module = "org.postgresql:postgresql", version.ref = "postgres" }

flyway-core = { module = "org.flywaydb:flyway-core" }
flyway-postgres = { module = "org.flywaydb:flyway-database-postgresql" }

############################
# Testing
############################
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
spring-boot-starter-jdbc-test = { module = "org.springframework.boot:spring-boot-starter-jdbc-test" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }

kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }
testcontainers-junit = { module = "org.testcontainers:testcontainers-junit-jupiter" }
testcontainers-postgres = { module = "org.testcontainers:testcontainers-postgresql" }

